AWSTemplateFormatVersion: 2010-09-09
Description: Linux Academy - AWS Essentials [Project Omega]


Parameters:

  # Project Name
    ProjectName:
      Description: Name of the Project
      Type: String

  # Project VPC CIDR
    VPCCIDR:
      Description: IP Range for the Project.
      Type: String
      Default: 10.0.0.0/16

   # Project Public Subnet 1
    PublicSubnet1CIDR:
      Description: An IPv4 CIDR block to associate with the VPC.
      Type: String
      Default: 10.0.0.0/24

  # Project Public Subnet 2
    PublicSubnet2CIDR:
      Description: An IPv4 CIDR block to associate with the VPC.
      Type: String
      Default: 10.0.1.0/24

  # Project Private Subnet 1
    PrivateSubnet1CIDR:
      Description: An IPv4 CIDR block to associate with the VPC.
      Type: String
      Default: 10.0.2.0/24

  # Project Private Subnet 2
    PrivateSubnet2CIDR:
      Description: An IPv4 CIDR block to associate with the VPC.
      Type: String
      Default: 10.0.3.0/24

  
Resources:

# Creating VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCIDR
      EnableDnsHostnames: true
    # tag
      Tags:
        - 
          Key: Name  
          Value: !Sub ${ProjectName} VPC
          

# Adding Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
    # tag
      Tags:
        -
          Key: Name
          Value: !Ref ProjectName

# Adding InternetGatewayAttachment  
# (required with Internet Gateway)
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

      
# Adding Public Subnet 1
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: "us-east-1a"
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - 
          Key: Name
          Value: !Sub ${ProjectName} Public Subnet 1

# Adding Public Subnet 2
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: "us-east-1b"
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - 
          Key: Name
          Value: !Sub ${ProjectName} Public Subnet 2

# Adding Private Subnet 1
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: "us-east-1a"
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - 
          Key: Name
          Value: !Sub ${ProjectName} Private Subnet 1


# Adding Private Subnet 2
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: "us-east-1b"
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - 
          Key: Name
          Value: !Sub ${ProjectName} Private Subnet 2


# Adding PUBLIC Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - 
          Key: Name
          Value: !Sub ${ProjectName} Public Routes

# Default Routing Rule - Public Rule  (Send all traffic to Internet Gateway)
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0  # Rule: send all traffic to Internet Gateway. (next line)
      GatewayId: !Ref InternetGateway

#  Applying routing rule to Public Subnet 1
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1   

 #  Applying routing rule to Public Subnet 2
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2



# Adding PRIVATE Route Table
  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC
      Tags: 
        - 
          Key: Name
          Value: !Sub ${ProjectName} Private Route

#   # Default Routing Rule - Private Subnet Rule
#   DefaultPrivateRoute1:
#     Type: AWS::EC2::Route
#     Properties:
#       RouteTableId: !Ref PrivateRouteTable1
#     #  DestinationCidrBlock: 0.0.0.0/0  # send all traffic to Nat Gateway (keep in inside the VPC)
#     #  NatGatewayId: !Ref NatGateway1
  
  #  Applying routing rule to Private Subnet 1
  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet1
  
 #  Applying routing rule to Private Subnet 2
  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet2



 #  Creating NACL
  NetACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPC
      Tags: 
        - 
          Key: "Name"
          Value: !Sub ${ProjectName} NACL

 # Network Access Rules [Egress = FALSE for INBOUND traffic and TRUE for OUTBOUND traffic]

 # INBOUND Rule # 1
  NetworkAclEntry1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0     # allowing everything
      NetworkAclId: !Ref NetACL
      RuleNumber: '100'
      Protocol: "-1"      # -1 for everything
      RuleAction: allow   # allow or deny
      Egress: 'false'   # FALSE for INBOUND traffic and TRUE for OUTBOUND traffic.
      PortRange:
        From: '0'
        To: '65535'
        
 # INBOUND Rule # 2
  # NetworkAclEntry2:
  #   Type: AWS::EC2::NetworkAclEntry
  #   Properties:      
  #     CidrBlock: 0.0.0.0/0  
  #     NetworkAclId: !Ref NetACL
  #     RuleNumber: '110'
  #     Protocol: "-1"
  #     RuleAction: allow
  #     Egress: 'false'   # FALSE for INBOUND traffic and TRUE for OUTBOUND traffic.
  #     PortRange:
  #       From: '0'
  #       To: '65535'
      

 # OUTBOUND Rule # 1
  NetworkAclEntry2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:      
      CidrBlock: 0.0.0.0/0  
      NetworkAclId: !Ref NetACL
      RuleNumber: '100'
      Protocol: "-1"
      RuleAction: allow
      Egress: 'true'   # FALSE for INBOUND traffic and TRUE for OUTBOUND traffic.
      PortRange:
        From: '0'
        To: '65535'